name = input ('whats your name? \n')
print ("hello", name)
mood = input ('how are you? \n')
print ("so you are" ,mood)
cheese = input ('what king of food do you like? \n')
print ("well",name, "i dont like",cheese)
